### PR TITLE
Provide a way to include all assets (issue #35)

### PR DESCRIPTION
**Pull request by laysent**
This PR tries to add feature to add all assets for plugin, not just chunks. In this way, resources handled by `file-loader` can also be added (#35).
Also, when I tried this version in my own project, I notice that it might be a bit annoying to use `fileBlacklist` to exclude every type of files that I don't want to include (too many assets). Thus, I also create an option named `fileWhitelist` to include resources. That might make things easier in some situation.

One thing I noticed is that `file-loader` provides an option to specify `publicPath` just for assets. However, that information seems to be lost when this plugin is doing its job. In code, it is using `publicPath` defined in `output`. It could be an issue, if these `publicPath` have different values. However, I am not able to find a way to work around this. Any hint will be very welcome.

### CODE REVIEW

**Comment by jarrybomb** [comment]
ty

**Comment by umpc** [comment]
Since a best solution to the question about differing ```publicPath``` values has not yet been found: 

Would it be acceptable to add a note related to that behavior to the Readme and merge this PR in the meantime?

Someone who wants to use this functionality, and has that issue, could open a new issue that hopefully includes a proposed solution that works best for that use-case.

I say this because I'm eagerly awaiting this functionality in the npm module, and would prefer not to keep track of when this is added. I doubt that I'm the only one working around this. 😁

I thank you, and the reviewer, for the work done on this feature!

**Comment by laysent** [comment]
@umpc Thanks for the suggestions. I have updated the README to point out this potential issue. :-)

**Comment by gkatsanos** [comment]
Is there any plan to merge this?

**Comment by alechill** [comment]
Agree, would be great to get this merged, but for now tests fail on....

```
Expected 'Html Webpack Plugin:
    <pre>
      TypeError: chunk.parents is not iterable

      - index.js:40 doesChunkBelongToHTML
        /Users/Alec/workspace/misc/forks/preload-webpack-plugin/index.js:40:30
```

@laysent Same thing occurs in real use, and seeing as I need to use it now, I forked yours and did a simple fix, PR'd it in your fork in case you want it https://github.com/laysent/preload-webpack-plugin/pull/1

**Comment by gkatsanos** [comment]
I am confused by the documentation/README. Reading it looks like you can already use it for all assets. But in reality it doesn't work? Am I missing something?

**Comment by laysent** [comment]
Hi @gkatsanos, @alechill has fixed an issue of loading all chunks, would you mind to try again and see if that works?
@alechill It seems you might need to sign the CLA as well. See above message from googlebot

**Comment by gkatsanos** [comment]
@laysent : the fix isn't on master/release yet right?

**Comment by alechill** [comment]
@laysent Thanks, CLA sorted 👍

**Comment by laysent** [comment]
@gkatsanos nope, it's only on my PR and hasn't been merged yet.

**Comment by gkatsanos** [comment]
@laysent alright, I'll wait for it to be merged and test !

**Comment by frlinw** [comment]
There is something to do on the naming:
- `asyncChunks` is pascal case when `all-assets` is kebab-case. Rename one or the other to be consistent
- `all` and `all-assets` will be a source of confusion. maybe rename `all` in `all-chunks` (or `allChunks`)

**Comment by laysent** [comment]
@frlinw Hi, thanks for the review. I have made it all pascal case.
Also, I changed `all` to `allChunks`. To ensure it will not break existing code, `all` is still available, but not mentioned in README. Also, I add warning when `all` is used.

**Comment by jeffposnick** [comment]
Thanks for everyone's patience—I'm going to merge into `master` now, and will cut a new minor v2 release with this and any other pending changes.

(Please note that we're also thinking about an upcoming v3 release which will be informed by the options available in v2 (including in this PR), but which might revisit some of the decisions around some of the defaults, and the names used in the public interface.)

**Comment by freezy** [comment]
So `fileWhitelist` didn't make it into v3 yet I suppose?

**Pull request merged**
