### PR TITLE
[fix] fix  duplicate outputs when using with multiple instances of HtmlWebpackPlugin

### PR DESCRIPTION
**Pull request by toxic-johann**
I found a way to fix [Duplicate outputs when using with multiple instances of HtmlWebpackPlugin](https://github.com/GoogleChrome/preload-webpack-plugin/issues/27).

It cause by two bug. 

1.  `filesToInclude` is shared by multiple compilation, which caused duplication.
2.  It hasn't check if the chunk belong to the page, so it will inject all the chunk into every page.

**solution**

1.   I move `filesToInclude` into each compilation. So they won't interfere with each other
2.  I check the chunk by renderedHash, which is used by htmlWebpackPlugin.

### CODE REVIEW

**Comment by toxic-johann** [comment]
I signed it!

**Comment by toxic-johann** [comment]
hmmmm... Can someone review the pr ?

**Comment by 9renpoto** [comment]
@toxic-johann Thanks! this PR works my project! 👍 

@addyosmani Please review it.

**Comment by jeffposnick** [comment]
@addyosmani has asked me to lend a hand with this repo.

I don't see any red flags with this PR, and I trust based on the reactions and comments that it solves a problem that many folks were running into, so I'm fine with merging.

My one question for @toxic-johann is whether you'd consider this a major or minor change from a semver perspective (i.e. does it "break" existing functionality that others might have depended on). I'm trying to determine whether to tag this new code `2.1.0` or `3.0.0` on npm.

**Comment by toxic-johann** [comment]
@jeffposnick just a minor change

**Comment by jeffposnick** [comment]
Thanks for confirming, and thanks for everyone's patience.

**Comment by jeffposnick** [comment]
(I'll publish 2.1.0 to `npm` soon—I've asked @addyosmani to add me as an owner there.)

**Comment by jeffposnick** [comment]
`2.1.0` is now live on npm, and tagged on GitHub: https://github.com/GoogleChromeLabs/preload-webpack-plugin/releases/tag/v2.1.0

**Pull request merged**
